# JPA
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/prediction
        username: root
        password: root
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
    data:
        redis:
            host: localhost
            port: 6379
    jwt:
        secret: j3H5Ld5nYmGWyULy6xwpOgfSH++NgKXnJMq20vpfd+8=t
        expiresIn: 86400000
    mail:
        host: smtp.gmail.com
        port: 587
        username: jaebindev945@gmail.com
        password: puxb vnxa zoxs rgdk
        properties:
            mail.smtp.debug: true
            mail.smtp.connectiontimeout: 1000 #1초
            mail.starttls.enable: true
            mail.smtp.auth: true

